---
- hosts: localhost
  name: Accept Upgrade EULA
  gather_facts: false
  vars_files: ../answerfile.yml
  tasks:
    - name: Accepts EULA
      nsxt_upgrade_eula_accept:
        hostname: "{{  nsxt_vip  }}"
        username: "{{  nsxt_admin_user  }}"
        password: "{{  nsxt_password  }}"
        validate_certs: "{{ validate_certs }}"

    