---
- hosts: localhost
  name: Configure NSX-T VIP and Accept EULA
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:
    - name: Configure NSX-T Manager VIP
      nsxt_virtual_ip:
          hostname: "{{ nsxt_manager_hostname }}"
          username: "{{ nsxt_admin_user }}"
          password: "{{ nsxt_password }}"
          validate_certs: "{{ nsxt_validate_certs }}"
          virtual_ip_address: "{{ nsxt_vip }}"
          state: "{{ state }}"

 # Checks that the NSX Manager is available prior to proceeding
    - name: Check NSX-T Manager VIP Status
      nsxt_manager_status:
          hostname: "{{ nsxt_vip }}"
          username: "{{ nsxt_admin_user }}"
          password: "{{ nsxt_password }}"
          validate_certs: "{{ nsxt_validate_certs }}"
          wait_time: 10

    - name: Pause for NSX-T Manager VIP to come up
      pause: 
        minutes: 5

# Disables NSX-T CEIP
    - name: Disable NSX-T Manager Telemetry 
      nsxt_rest:
          hostname: "{{ nsxt_vip }}"
          username: "{{ nsxt_admin_user }}"
          password: "{{ nsxt_password }}"
          validate_certs: "{{ nsxt_validate_certs }}"
          method: put
          path: /api/v1/telemetry/agreement
          content:
            {
              "_revision": 1,
              "id": "TelemetryAgreementIdentifier",
              "resource_type": "TelemetryAgreement",
              "telemetry_agreement_displayed": true
            }



