---
- hosts: localhost
  name: Initiate Upgrade of Upgrade Coordinator
  gather_facts: false
  vars_files: ../answerfile.yml
  tasks:
    - name: Upgrade Upgrade Coordinator
      nsxt_upgrade_uc:
        hostname: "{{  nsxt_vip  }}"
        username: "{{  nsxt_admin_user  }}"
        password: "{{  nsxt_password  }}"
        validate_certs: "{{ validate_certs }}"

    