---
- hosts: localhost
  name: Create NSX-T Uplink profiles (Compute - Edge)
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:
    - name: Create a Uplink Profile - COMPUTE
      nsxt_uplink_profiles:
          hostname: "{{ nsxt_vip }}"
          username: "{{ nsxt_admin_user }}"
          password: "{{ nsxt_password }}"
          validate_certs: "{{ nsxt_validate_certs }}"
          display_name: "{{ nsxt_compute_uplink_profile_name }}"
          resource_type: "UplinkHostSwitchProfile"
          teaming:
            active_list:
            - uplink_name: "{{ nsxt_teaming_policy_esxi_link01 }}"
              uplink_type: PNIC
            - uplink_name: "{{ nsxt_teaming_policy_esxi_link02 }}"
              uplink_type: PNIC              
            policy: LOADBALANCE_SRCID
          named_teamings:
          - name: "{{ nsxt_named_teaming_policy_name_01 }}"
            active_list:
            - uplink_name: "{{ nsxt_teaming_policy_esxi_link01 }}"
              uplink_type: PNIC
            policy: "FAILOVER_ORDER"
          - name: "{{ nsxt_named_teaming_policy_name_02 }}"
            active_list:
            - uplink_name: "{{ nsxt_teaming_policy_esxi_link02 }}"
              uplink_type: PNIC
            policy: "FAILOVER_ORDER"
          transport_vlan: "{{ nsxt_compute_uplink_profile_vlan }}"
          state: "{{ state }}"

    - name: Create a Uplink Profile - EDGE
      nsxt_uplink_profiles:
          hostname: "{{ nsxt_vip }}"
          username: "{{ nsxt_admin_user }}"
          password: "{{ nsxt_password }}"
          validate_certs: "{{ nsxt_validate_certs }}"
          display_name: "{{ nsxt_edge_uplink_profile_name }}"
          mtu: "{{ nsxt_mtu }}"
          resource_type: "UplinkHostSwitchProfile"
          teaming:
            active_list:
            - uplink_name: "{{ nsxt_teaming_policy_edge_link01 }}"
              uplink_type: PNIC
            - uplink_name: "{{ nsxt_teaming_policy_edge_link02 }}"
              uplink_type: PNIC                       
            policy: LOADBALANCE_SRCID  
          named_teamings:
          - name: "{{ nsxt_named_teaming_policy_name_01 }}"
            active_list:
            - uplink_name: "{{ nsxt_teaming_policy_edge_link01 }}"
              uplink_type: PNIC
            policy: "FAILOVER_ORDER"
          - name: "{{ nsxt_named_teaming_policy_name_02 }}"
            active_list:
            - uplink_name: "{{ nsxt_teaming_policy_edge_link02 }}"
              uplink_type: PNIC
            policy: "FAILOVER_ORDER"
          transport_vlan: "{{ nsxt_edge_uplink_profile_vlan }}"
          state: "{{ state }}"



  