---
- hosts: localhost
  name: Create Transport Node Collection and attach to {{ nsxt_compute_cluster_name }}
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:
    - name: Create transport node collection
      nsxt_transport_node_collections:
        hostname: "{{ nsxt_vip }}"
        username: "{{ nsxt_admin_user }}"
        password: "{{ nsxt_password }}"
        validate_certs: "{{ nsxt_validate_certs }}"
        display_name: "TNC1"
        resource_type: "TransportNodeCollection"
        description: "Transport Node Collections 1"
        compute_manager_name: "{{ nsxt_compute_manager_display_name }}"
        cluster_name: "{{ nsxt_compute_cluster_name }}"
        transport_node_profile_name: "{{ nsxt_transportnode_profile_name }}"
        state: present
