---
- hosts: localhost
  name: Upload MUB to NSX-T Manager
  gather_facts: false
  vars_files: ../answerfile.yml
  tasks:
    - name: Upload MUB to NSX-T Manager
      nsxt_upgrade_upload_mub:
        hostname: "{{  nsxt_sa_vip  }}"
        username: "{{  nsxt_admin_user  }}"
        password: "{{  nsxt_password  }}"
        validate_certs: "{{ validate_certs }}"
        url: "{{ nsxt_upgrade_mub_url }}"

    