---
- hosts: localhost
  name: Initiate Upgrade Pre-checks
  gather_facts: false
  vars_files: ../answerfile.yml
  tasks:
    - name: Run and abort upgrade prechecks
      nsxt_upgrade_prechecks:
        hostname: "{{ nsxt_vip }}"
        username: "{{ nsxt_admin_user }}"
        password: "{{ nsxt_password }}"
        validate_certs: "{{ validate_certs }}"
        state: '{{ state }}'