---
- hosts: localhost
  name: Lab Deployment
  gather_facts: false
  vars_prompt:
    - name: "vcenter_password"
      prompt: "What is the vCenter Password? "
      private: yes


  vars_files: answerfile.yml

  tasks:
    - name: setting fact
      set_fact:
        vcenter_password: "{{ vcenter_password }}"
        nsxt_password: "{{ nsxt_password }}"        


############################################################
######### NSX-T Infrastructure Playbooks Section  ##########
############################################################ 
#- import_playbook: playbooks/deploy/01-deploy-nsxtmanager.yml
#- import_playbook: playbooks/deploy/02-configure-nsxtmanager-vip-eula.yml
#- import_playbook: playbooks/deploy/03-configure-nsxtmanager-license.yml
#- import_playbook: playbooks/deploy/04-configure-compute-manager.yml
#- import_playbook: playbooks/deploy/05-configure-nsxtmanager-uplinkprofiles.yml
#- import_playbook: playbooks/deploy/06-configure-nsxtmanager-transportzones.yml
#- import_playbook: playbooks/deploy/07-configure-nsxtmanager-ippools.yml
#- import_playbook: playbooks/deploy/08-configure-nsxtmanager-transportnodesprofiles.yml
#- import_playbook: playbooks/deploy/09-configure-nsxtmanager-transportnodes.yml
#- import_playbook: playbooks/deploy/10-deploy-edgenodes-non-nested.yml
#- import_playbook: playbooks/deploy/11-configure-nsxtmanager-edgeclusters.yml

############################################################
#########    NSX-T Federation Playbooks Section   ##########
############################################################ 
#- import_playbook: playbooks/deploy/12-deploy-nsxt-global-manager-sa.yml
#- import_playbook: playbooks/13-configure-nsxt-global-manager-sa-vip.yml
#- import_playbook: playbooks/14-configure-nsxt-global-manager-sa-active.yml

