---
- hosts: localhost
  name: Lab Upgrade
  gather_facts: false
  vars_files: answerfile.yml
 

# Infrastructure Deployment # 
- import_playbook: playbooks/201-upload-mub-to-nsxt-manager.yml
- import_playbook: playbooks/202-accept-upgrade-eula.yml
- import_playbook: playbooks/203-upgrade-upgrade-coordinator.yml
- import_playbook: playbooks/204-upgrade-plan-hosts-edge.yml
- import_playbook: playbooks/205-upgrade-run-pre-checks.yml
- import_playbook: playbooks/206-upgrade-run.yml